describe('Create Truck Test', () => {
  it('Create a valid truck and verify if it was created', () => {
    cy.viewport(1366, 768)
    cy.visit('/')
    cy.get('#email').type('maia@eletric-go.com',{delay: 100}).should('have.value', 'maia@eletric-go.com')
    cy.get('#password').type('12345',{delay: 100}).should('have.value', '12345')
    cy.get('#go').click()
    cy.wait(3000)
    cy.get('#createTruck').click()
    cy.wait(1500)
    cy.contains('Create Truck')
    cy.get('#Plate').type(' ').clear()
    cy.get('#Plate').clear().type('10-11-BB',{delay: 100}).should('have.value', '10-11-BB')
    cy.get('#Tare').clear().type('7500',{delay: 100}).should('have.value', '7500')
    cy.get('#MassCapacity').clear().type('4300',{delay: 100}).should('have.value', '4300')
    cy.get('#Battery').clear().type('80',{delay: 100}).should('have.value', '80')
    cy.get('#Autonomy').clear().type('100',{delay: 100}).should('have.value', '100')
    cy.get('#Hours').clear().type('1',{delay: 100}).should('have.value', '1')
    cy.get('#Minutes').clear().type('0',{delay: 100}).should('have.value', '0')
    cy.get('#Seconds').clear().type('0',{delay: 100}).should('have.value', '0')
    cy.get('#submit').click()
    cy.wait(3000)
    cy.get('#ok').click()
    cy.wait(1500)
    cy.get('#getTrucks').click()
    cy.get('#myInput').type('10-11{enter}',{delay: 100}).should('have.value', '10-11')
    cy.get('mat-row').should('be.visible')
    cy.wait(3000)
    cy.get('#menuu').click()
    cy.wait(500)
    cy.get('#logout').click()
  })
  
  it('Create an invalid truck', () => {
    cy.visit('/')
    cy.get('#email').type('maia@eletric-go.com',{delay: 100}).should('have.value', 'maia@eletric-go.com')
    cy.get('#password').type('12345',{delay: 100}).should('have.value', '12345')
    cy.get('#go').click()
    cy.wait(3000)
    cy.get('#createTruck').click()
    cy.wait(1500)
    cy.contains('Create Truck')
    cy.get('#Plate').type(' ').clear()
    cy.get('#Plate').clear().type('01-11-BB',{delay: 100}).should('have.value', '01-11-BB')
    cy.get('#Tare').clear().type('7500',{delay: 100}).should('have.value', '7500')
    cy.get('#MassCapacity').clear().type('4300',{delay: 100}).should('have.value', '4300')
    cy.get('#Battery').clear().type('-80',{delay: 100}).should('have.value', '-80')
    cy.get('#Autonomy').clear().type('100',{delay: 100}).should('have.value', '100')
    cy.get('#Hours').clear().type('1',{delay: 100}).should('have.value', '1')
    cy.get('#Minutes').clear().type('0',{delay: 100}).should('have.value', '0')
    cy.get('#Seconds').clear().type('0',{delay: 100}).should('have.value', '0')
    cy.get('#submit').click()
    cy.wait(3000)
    cy.contains("energy can't be negative")
    cy.wait(3000)
    cy.get('#menuu').click()
    cy.wait(500)
    cy.get('#logout').click()
  })
  
  it('Update the created truck and verify if it was updated', () => {
    cy.visit('/')
    cy.get('#email').type('maia@eletric-go.com',{delay: 100}).should('have.value', 'maia@eletric-go.com')
    cy.get('#password').type('12345',{delay: 100}).should('have.value', '12345')
    cy.get('#go').click()
    cy.wait(3000)
    cy.get('#updateTruck').click()
    cy.wait(1500)
    cy.contains('Update Truck')
    cy.get('#Plate').select('10-11-BB')
    cy.wait(500)
    cy.get('#Tare').clear()
    cy.get('#Tare').type('8000',{delay: 100}).should('have.value', '8000')
    cy.get('#submit').click()
    cy.wait(3000)
    cy.contains('Truck updated sucessfully!')
    cy.get('#ok').click()
    cy.wait(1500)
    cy.get('#getTrucks').click()
    cy.get('#myInput').type('10-11{enter}',{delay: 100}).should('have.value', '10-11')
    cy.contains('8000')
    cy.wait(3000)
    cy.get('#menuu').click()
    cy.wait(500)
    cy.get('#logout').click()
  })
  
  it('Delete the created truck and verify if it was deleted', () => {
    cy.visit('/')
    cy.get('#email').type('maia@eletric-go.com',{delay: 100}).should('have.value', 'maia@eletric-go.com')
    cy.get('#password').type('12345',{delay: 100}).should('have.value', '12345')
    cy.get('#go').click()
    cy.wait(3000)
    cy.get('#getTrucks').click()
    cy.wait(1500)
    cy.get('#myInput').type('10-11{enter}',{delay: 100}).should('have.value', '10-11')
    cy.get('#10-11-BB').click()
    cy.wait(3000)
    cy.get('#myInput').type('{enter}',{delay: 100}).should('have.value', '10-11')
    cy.wait(3000)
    cy.get('#menuu').click()
    cy.wait(500)
    cy.get('#logout').click()
  })
})

describe('Inhibit Truck Test', () => {
  it('Inhibit a truck and verify if it was inhibited', () => {
    cy.viewport(1366, 768)
    cy.visit('/')
    cy.get('#email').type('maia@eletric-go.com',{delay: 100}).should('have.value', 'maia@eletric-go.com')
    cy.get('#password').type('12345',{delay: 100}).should('have.value', '12345')
    cy.get('#go').click()
    cy.wait(3000)
    cy.get('#createTruck').click()
    cy.wait(1500)
    cy.contains('Create Truck')
    cy.get('#Plate').type(' ').clear()
    cy.get('#Plate').clear().type('10-11-BB',{delay: 100}).should('have.value', '10-11-BB')
    cy.get('#Tare').clear().type('7500',{delay: 100}).should('have.value', '7500')
    cy.get('#MassCapacity').clear().type('4300',{delay: 100}).should('have.value', '4300')
    cy.get('#Battery').clear().type('80',{delay: 100}).should('have.value', '80')
    cy.get('#Autonomy').clear().type('100',{delay: 100}).should('have.value', '100')
    cy.get('#Hours').clear().type('1',{delay: 100}).should('have.value', '1')
    cy.get('#Minutes').clear().type('0',{delay: 100}).should('have.value', '0')
    cy.get('#Seconds').clear().type('0',{delay: 100}).should('have.value', '0')
    cy.get('#submit').click()
    cy.wait(3000)
    cy.get('#ok').click()

    cy.get('#getTrucks').click()
    cy.wait(1500)
    cy.get('#myInput').type('10-11-BB{enter}',{delay: 100}).should('have.value', '10-11-BB')
    cy.get('#I10-11-BB').click()
    cy.wait(3000)
    cy.get('#active').click()
    cy.get('#myInput').type('{enter}',{delay: 100}).should('have.value', '10-11-BB')
    cy.get('mat-row').should('be.visible')
    cy.wait(3000)
    cy.get('#menuu').click()
    cy.wait(500)
    cy.get('#logout').click()
  })

  it('Activate a truck and verify if it was activated', () => {
    cy.viewport(1366, 768)
    cy.visit('/')
    cy.get('#email').type('maia@eletric-go.com',{delay: 100}).should('have.value', 'maia@eletric-go.com')
    cy.get('#password').type('12345',{delay: 100}).should('have.value', '12345')
    cy.get('#go').click()
    cy.wait(3000)

    cy.get('#getTrucks').click()
    cy.wait(1500)
    cy.get('#myInput').type('10-11-BB{enter}',{delay: 100}).should('have.value', '10-11-BB')
    cy.get('#A10-11-BB').click()
    cy.wait(3000)
    cy.get('#inhibt').click()
    cy.get('#myInput').type('{enter}',{delay: 100}).should('have.value', '10-11-BB')
    cy.get('mat-row').should('be.visible')
    cy.wait(3000)
    cy.get('#10-11-BB').click()
    cy.wait(3000)
    cy.get('#menuu').click()
    cy.wait(500)
    cy.get('#logout').click()
  })
})
