describe('Anonymize User Test', () => {
    it('Anonymize User and verify if it was anonymized', () => {
        cy.viewport(1366, 768)
        cy.visit('/')
        cy.get('#email').type('admin@eletric-go.com',{delay: 100}).should('have.value', 'admin@eletric-go.com')
        cy.get('#password').type('12345',{delay: 100}).should('have.value', '12345')
        cy.get('#go').click()
        cy.wait(3000)
        cy.get('#register').click()
        cy.contains('Register User')
        cy.get('#firstName').type(' ').clear()
        cy.get('#firstName').clear().type('New',{delay: 100}).should('have.value', 'New')
        cy.get('#lastName').clear().type('User',{delay: 100}).should('have.value', 'User')
        cy.get('#email').clear().type('user@eletric-go.com',{delay: 100}).should('have.value', 'user@eletric-go.com')
        cy.get('#password').clear().type('12345',{delay: 100}).should('have.value', '12345')
        cy.get('#confirmPassword').clear().type('12345',{delay: 100}).should('have.value', '12345')
        cy.get('#phone').clear().type('912345678',{delay: 100}).should('have.value', '912345678')
        cy.get('#name').select('Warehouse Manager')
        cy.get('#submit').click()
        cy.wait(3000)
        cy.get('#ok').click()
        cy.wait(1500)

        cy.get('#anonymize').click()
        cy.wait(1500)
        cy.contains('Anonymize User')
        cy.get('#User').select('New User - user@eletric-go.com - Warehouse Manager')
        cy.wait(500)
        cy.get('#submit').click()
        cy.wait(3000)
        cy.contains('User anonymized!')
        cy.get('#ok').click()
        cy.wait(3000)
        cy.get('#menuu').click()
        cy.wait(500)
        cy.get('#logout').click()
    })
})