@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor GL
participant "sPA: SPA" as sPA
participant "logística: Logística" as MDL 


activate GL
GL ->sPA : Asks to delete a trip
activate sPA

sPA --> MDL : GET /trips body:data
activate MDL

MDL --> sPA :  200 body(trips)

deactivate MDL

sPA --> GL : shows all the trips

deactivate sPA

GL --> sPA : selects the trip to delete

activate sPA

sPA --> MDL : DELETE /trips body:data

activate MDL

MDL --> sPA :  status:200

deactivate MDL

sPA --> GL : success message

deactivate sPA

deactivate GL



@enduml