@startuml
actor GL
GL -> EletricGo: Inicia criação de uma caminho
activate EletricGo
EletricGo --> GL : Solicita dados
deactivate

GL -> EletricGo: Introduz dados
activate EletricGo
EletricGo --> GL : Mostra dados e solicita confirmação
deactivate

GL -> EletricGo: Confirma
activate EletricGo
EletricGo --> GL : Informa o sucesso da operação
deactivate EletricGo
@enduml