@startuml
actor GL
GL -> EletricGo: Inicia leitura de um caminho
activate EletricGo
EletricGo --> GL : Solicita dados
deactivate

GL -> EletricGo: Introduz o que pretende ler
activate EletricGo
EletricGo --> GL : Mostra dados e solicita confirmação
deactivate

GL -> EletricGo: Confirma
activate EletricGo
EletricGo --> GL : Informa o sucesso da operação
deactivate EletricGo
@enduml