@startuml
actor GA
GA -> EletricGo: Inicia atualização de um armazém
activate EletricGo
EletricGo --> GA : Solicita dados
deactivate

GA -> EletricGo: Introduz campos que pretende atualizar
activate EletricGo
EletricGo --> GA : Mostra dados e solicita confirmação
deactivate

GA -> EletricGo: Confirma
activate EletricGo
EletricGo --> GA : Informa o sucesso da operação
deactivate EletricGo
@enduml