@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "sPA: SPA" as sPA
participant "MDA: MDA" as MDA 
participant "WarehousesController" as controller
participant "WarehouseService" as service
participant "IWarehouseRepository" as repository




activate sPA
sPA -> MDA : post /Warehouses
activate MDA

MDA -> controller :  create

activate controller

controller-> service : AddAsync

activate service

service -> Warehouse** : create

service -> repository : AddAsync
activate repository
service-> repository: commitAsync

deactivate repository
service --> controller : warehouseDto
deactivate service

alt sucess
controller --> MDA : status 201 (Created)

MDA --> sPA : success message


else insuccess
controller --> MDA : status 400 (Bad Request)
deactivate controller

MDA --> sPA : insuccess message

deactivate MDA
end
deactivate sPA



@enduml