@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "sPA: SPA" as sPA
participant "MDA: MDA" as MDA 
participant "DeliveriesController" as controller
participant "DeliveryService" as service
participant "IDeliveryRepository" as repository




activate sPA
sPA -> MDA : DELETE /Deliveries/HardDelete

activate MDA

MDA -> controller :  HardDelete

activate controller

controller-> service : DeleteAsync

activate service

service -> repository : GetByIdAsync
activate repository

repository --> service : delivery


service -> repository : Remove

service -> repository : CommitAsync

deactivate repository

service --> controller : dto
deactivate service

alt success
controller --> MDA : status 200 (Ok)

MDA --> sPA : success message
else NotFound
controller --> MDA : status 404 (Not Found)

MDA --> sPA : insuccess message
else BadRequest
controller --> MDA : status 400 (Bad Request)

MDA --> sPA : insuccess message
end
deactivate controller

deactivate MDA


deactivate sPA



@enduml