@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor GF

participant "sPA: SPA" as sPA
participant "logística: Logística" as MDL 

activate GF
GF ->sPA : Asks to update a truck
activate sPA

sPA --> MDL : GET /trucks body:data
activate MDL

MDL --> sPA :  200 body(trucks)

deactivate MDL

sPA --> GF : shows all the trucks

deactivate sPA

GF --> sPA : selects the truck to update and the updated data

activate sPA

sPA --> MDL : PUT /trucks body:data

activate MDL

MDL --> sPA :  status:200

deactivate MDL

sPA --> GF : success message

deactivate sPA

deactivate GF



@enduml