@startuml


node "SPA" as SPA {
  component Browser {
   [SPA UI]
  }
}

node "localhost:5001" as ARM {
  [ARMAZEM] as armazem
}

node "localhost:3000" as LOG {
  [LOGISTICA] as logistica
}

node "PLANEAMENTO" as PLAN {
  [PLANEAMENTO] as planeamento
}

SPA -- ARM: http/s
SPA -- LOG: http
SPA -- PLAN
ARM -- LOG

@enduml
