@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "GA" as GA
participant "DeliveriesComponent" as COMP
participant "DeliveriesServiceService" as SS
participant "MDA: MDA" as MDA 
participant "DeliveriesController" as controller
participant "DeliveryService" as service
participant "IDeliveryRepository" as repository



GA-> COMP : asks to list deliveries
activate COMP
COMP -> COMP : getDeliveries()
activate COMP
COMP -> SS : getAllDeliveries()
activate SS
SS -> MDA : GET /Deliveries/listAll
note left
  Depending on the selected filter (id, 
  warehouse, dates) 
  the request and the methods will be 
  different, changing the method's name
  and implementation
end note

activate MDA

MDA -> controller :  GetAll

activate controller

controller-> service : GetAllAsync

activate service

service -> repository : GetAllAsync
activate repository

repository --> service : list<Delivery>

service -> service : listDto = list.convertAll<DeliveryDto>

deactivate repository
service --> controller : listDto
deactivate service


controller --> MDA : status 200 (Ok)
deactivate controller

MDA --> SS : success message
deactivate MDA
SS --> COMP : success message
deactivate SS
GA<-- COMP : success message

deactivate MDA


deactivate COMP



@enduml