@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor GA
participant "sPA: SPA" as sPA
participant "MDA: MDA" as MDA 


activate GA
GA ->sPA : Asks to read a delivery
activate sPA

sPA --> MDA : GET /deliveries body:data
activate MDA

MDA --> sPA :  200 body(deliveries)

deactivate MDA

sPA --> GA : shows all the deliveries

deactivate sPA

GA --> sPA : selects the delivery and data wanted

activate sPA



sPA --> GA : presents the data

deactivate sPA

deactivate GA



@enduml